### ISSUE TITLE
wrap apb tool in docker image

### ISSUE THREAD

**Issue by maleck13** [fusor/ansible-playbook-bundle#102]
Wonder if creating an apb docker image would be a good way to go here?
Setting up python and the virtural env took a while for different reasons. Where as being able to do ``` docker run fusor/apb init org/image ``` might provide a better option for those not familiar with python ?

**Comment by jmontleon** [comment]
This isn't a bad idea and I've considered it as a possibility in the past as well. I haven't had a good idea on how we'd write to the host filesystem without requiring users pass in -v/mount options to mount the filesystem somewhere specific though. Do you have a thought?

In the short term, if you're using Fedora or EL7 there are also Copr repos available for RPM installs:
https://github.com/fusor/ansible-playbook-bundle#installing-the-apb-tool

The packages auto rebuild after each commit to the git repo so they're generally pretty up to date.

**Comment by jmontleon** [comment]
As a starting point for a Dockerfile:

```
FROM centos:7

RUN curl https://copr.fedorainfracloud.org/coprs/g/ansible-service-broker/ansible-service-broker-latest/repo/epel-7/group_ansible-service-broker-ansible-service-broker-latest-epel-7.repo -o /etc/yum.repos.d/asb.repo
RUN yum -y install epel-release && yum -y install apb && yum clean all

WORKDIR /mnt

ENTRYPOINT ["apb"]
CMD ["-h"]
```

`docker build -t apb .`

`docker run --privileged -u $(id -u) -v $(pwd):/mnt apb init foo/bar`

Things that aren't great about this:
- You'll probably get an selinux denial mounting the directory unless you use privileged or set the context to make docker happy.
- Have to specify -u with something like $(id -u) or the directory is created as root
- Have to specify a mount with something like -v $(pwd):/mnt
- apb output is a little misleading `Initializing /mnt/bar for an APB.`

You can make this all a little less ugly for repeated runs with an alias:
`alias apb='docker run --privileged -u $(id -u) -v $(pwd):/mnt apb'`

```
$ apb init foo/bar
Initializing /mnt/bar for an APB.
Generating playbook files
Successfully initialized project directory at: /mnt/bar
Please run *apb prepare* inside of this directory after editing files.

$ cd bar

$ apb prepare
Finished writing dockerfile.
```

**Comment by jwmatthews** [comment]
@maleck13 great suggestion, thank you.

**Comment by maleck13** [comment]
@jmontleon having the alias seems a good compromise

**Comment by tchughesiv** [comment]
something like this should allow you to avoid --privileged flag
```shell
$ docker run --rm -u $(id -u):$(id -g) -v $(pwd):/mnt:z apb init foo/bar
```

**Comment by tchughesiv** [comment]
you could also add an atomic "run" label for folks who want to easily use atomic to exec... instead of relying on an alias

**Comment by jmontleon** [comment]
Thanks @tchughesiv, I have inncorporated your suggestions.

**Comment by maleck13** [comment]
@jmontleon Great stuff guys tried out the docker image locally and works great!
