### ISSUE TITLE
Add Basic Auth support for dev endpoints

### ISSUE THREAD

**Issue by dymurray** [fusor/ansible-playbook-bundle#108]
We need a mechanism to allow the user to pass in user/pass when using tools such as 'apb list' and 'apb push' so that we don't need to disable basic_auth in the broker. Ideally this would try to use creds stored in kubeconfig.

**Comment by jmrodri** [comment]
Are we sure we want this? I think right now if dev is turned on basic auth should be disabled.

**Comment by aweiteka** [comment]
I don't know of a scenario where one would not be authenticated to the cluster via kubeconfig. My use case is for `apb list|push` to use those credentials. It appears that today the endpoint must be unauthenticated when using apb CLI. I suggest we always use auth from kubeconfig or fail. (Unauth'd dev workflows set up negative dev/test precedence.) Long term I think this capability should be in oc CLI, at least as [an extension](https://trello.com/c/o6UiTkxv).

cc @tchughesiv @jcpowermac

**Comment by jwmatthews** [comment]
I agree we can do better to support auth with the tooling.  

@aweiteka FYI, auth in this perspective is using a shared secret between Service Catalog and Broker, not related to ~/.kube/config at moment, in future we might be able to add a role to the logged in user and use their token against the api server, not there yet.

@jmrodri security team has suggested same to us in regard to disabling security features for dev/test is bad practice and to be avoided.

Created this trello card on backlog to track the work:
https://trello.com/c/DSTWDi0K

**Comment by aweiteka** [comment]
> auth in this perspective is using a shared secret between Service Catalog and Broker, not related to ~/.kube/config at moment

That makes more sense. Thanks.

**Comment by dymurray** [comment]
This has been added within the past month. Support for bearer and basic auth works now.
