### ISSUE TITLE
Role Binding uses name as an alias for role_ref_name

### ISSUE THREAD

**Issue by slaskawi** [fusor/ansible-playbook-bundle#119]
The documentation states that `name` is an alias for `role_ref_name` ([here's a link](https://github.com/ansible/ansible-kubernetes-modules/blob/master/library/openshift_v1_role_binding.py#L109-L110)). This is simply wrong. It is possible to have a Role Binding with different `RoleRefName` and `Name`:

```
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  creationTimestamp: 2017-09-25T08:35:15Z
  labels:
    template: jdg-caching-service
# Name = infinispan-app-view
  name: infinispan-app-view
  namespace: myproject
  resourceVersion: "1989"
  selfLink: /oapi/v1/namespaces/myproject/rolebindings/infinispan-app-view
  uid: 7425976b-a1cc-11e7-b3a4-54ee751d46e3
roleRef:
# Role Ref Name = view
  name: view
subjects:
- kind: ServiceAccount
  name: infinispan-app
  namespace: myproject
userNames:
- system:serviceaccount:myproject:infinispan-app

```

**Comment by rthallisey** [comment]
> The documentation states that name is an alias for role_ref_name (here's a link). This is simply 
> wrong. It is possible to have a Role Binding with different RoleRefName and Name:
>
You're creating a new RoleBinding with the the name ```name: infinispan-app-view``` and you're referencing an OpenShift provided RoleBinding ``` roleRef: name: view``` to give permissions to you're new RoleBinding.  So you end up with the RoleBinding ```infinispan-app-view``` with view permissions. I think it's correct the way it is.

Feel free to open an issue with the [ansible module](https://github.com/ansible/ansible-kubernetes-modules/blob/master/library/openshift_v1_role_binding.py) if you disagree.
