### ISSUE TITLE
missing docker.io/ansibleplaybookbundle/apb

### ISSUE THREAD

**Issue by matihost** [fusor/ansible-playbook-bundle#172]
`docker pull docker.io/ansibleplaybookbundle/apb ` results with:

`Using default tag: latest
Trying to pull repository docker.io/ansibleplaybookbundle/apb ... 
repository docker.io/ansibleplaybookbundle/apb not found: does not exist or no pull access`

**Comment by rthallisey** [comment]
```ansibleplaybookbundle/apb``` isn't a valid apb.  Here's a list of apbs available in the ansibleplaybookbundle dockerhub: https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=ansibleplaybookbundle&starCount=0

Try using one of those and report back if there are any issues.

**Comment by matihost** [comment]
I just wanted to install `apb` CLI via instruction
https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/apb_cli.md#running-from-a-container

This way seems the best for me as i'm not operating from RH/Centos.

Is there a typo in documentation?
Shouldn't it be `docker pull ansibleplaybookbundle/apb-tools` ?

**Comment by jmontleon** [comment]
It should be apb-tools. It was changed a day or two ago. I'll update the docs, sorry about that.

**Comment by matihost** [comment]
No problem. Thanks!
