### ISSUE TITLE
Unable to "apb push -o" using local openshift registry

### ISSUE THREAD

**Issue by rwsu** [fusor/ansible-playbook-bundle#174]
When I do a "apb push -o" I am seeing "Execption occurred! 'authorization". It is unclear to me what is the authorization error and how to fix it. I have setup the ansible service broker to use the local openstack registry. Please see config file and details below. 

[vagrant@localhost mariadb-apb]$ apb push -o
version: 1.0
id: 5a9eb5f8-cbde-4e62-a30a-9fa30006fc9a
name: tripleo-k8s-mariadb
image: tripleo/tripleo-k8s-mariadb
description: This is a sample application generated by apb init
bindable: True
async: optional
metadata:
  displayName: tripleo-k8s-mariadb
plans:
  - name: tripleo-k8s-mariadb
    description: This plan deploys mariadb on k8s
    free: True
    metadata: {}
    parameters: []

Found registry IP at: 172.30.1.1:5000
Building image with the tag: 172.30.1.1:5000/openshift/tripleo-k8s-mariadb
Exception occurred! 'authorization'

The openshift environment was brought up using 
ORIGIN_VERSION=v3.7.0 ./run_latest_build.sh

[vagrant@localhost mariadb-apb]$ oc status
In project ansible-service-broker on server https://127.0.0.1:8443

https://asb-1338-ansible-service-broker.172.17.0.1.nip.io (reencrypt) to pod port port-1338 (svc/asb)
  dc/asb deploys docker.io/ansibleplaybookbundle/origin-ansible-service-broker:latest 
    deployment #1 deployed about an hour ago - 1 pod

svc/asb-etcd - 172.30.134.117:2379
  dc/asb-etcd deploys quay.io/coreos/etcd:latest 
    deployment #1 deployed about an hour ago - 1 pod

1 warning identified, use 'oc status -v' to see details.

[vagrant@localhost mariadb-apb]$ oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

[vagrant@localhost ansible-service-broker]$ cat /etc/ansible-service-broker/config.yaml 
broker:
  devbroker: true
registry:
  - type: local_openshift
    name: lo
    namespaces:
      - openshift
    white_list:
      - ".*-apb$"

**Comment by rthallisey** [comment]
Did you ```oc login``` before you ran ```oc push -o```?
See if ```oc whoami``` returns a token.

**Comment by jwmatthews** [comment]
@dymurray any thoughts?

**Comment by dymurray** [comment]
I agree with @rthallisey It looks like it is failing on this line: https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/20ff568f96b43480d90f309dc123d3f83eaf6749/src/apb/engine.py#L853 which implies that the loading the user config isn't working. I would ensure you have logged in as `admin` and if that still fails please paste all of the output of your `apb push -o`.

**Comment by rwsu** [comment]
oc whoami was reporting system:admin.

After switching to logging in as admin/admin and switching to running apb-tools from container instead of rpm (rpm repo is broken), I now see:

[vagrant@localhost mariadb-apb]$ apb push -o
version: 1.0
id: 5a9eb5f8-cbde-4e62-a30a-9fa30006fc9a
name: tripleo-k8s-mariadb
image: tripleo/tripleo-k8s-mariadb
description: This is a sample application generated by apb init
bindable: True
async: optional
metadata:
  displayName: tripleo-k8s-mariadb
plans:
  - name: tripleo-k8s-mariadb
    description: This plan deploys mariadb on k8s
    free: True
    metadata: {}
    parameters: []

('Exception occurred trying to find docker-registry service: %s', ApiException())
Exception occurred! unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by rthallisey** [comment]
@rwsu do you see a docker-registry pod running in the default namespace?

**Comment by dymurray** [comment]
@rwsu more specifically to @rthallisey's point: The code is looking for a service name `docker-registry` in namespace `default`. If you can do `oc get svc -n default` and check if docker-registry exists (or if it does exist are the pods running?) II am going to add some better error handling here because these are ugly messages.

**Comment by rwsu** [comment]
It appears the pods are running:

[vagrant@localhost ~]$ oc get svc -n default
NAME              CLUSTER-IP     EXTERNAL-IP   PORT(S)                   AGE
docker-registry   172.30.1.1     <none>        5000/TCP                  22m
kubernetes        172.30.0.1     <none>        443/TCP,53/UDP,53/TCP     22m
router            172.30.73.28   <none>        80/TCP,443/TCP,1936/TCP   22m

[vagrant@localhost ~]$ oc get pods --all-namespaces=true
NAMESPACE                           NAME                                  READY     STATUS      RESTARTS   AGE
ansible-service-broker              asb-1-p5pkt                           1/1       Running     0          21m
ansible-service-broker              asb-etcd-1-b7dwp                      1/1       Running     0          21m
default                             docker-registry-1-wtrrk               1/1       Running     0          22m
default                             persistent-volume-setup-s28z9         0/1       Completed   0          22m
default                             router-1-hld2f                        1/1       Running     0          22m
kube-service-catalog                apiserver-225483863-vskxb             2/2       Running     0          22m
kube-service-catalog                controller-manager-1159488142-lftl9   1/1       Running     2          22m
openshift-template-service-broker   apiserver-848rw                       1/1       Running     0          22m

**Comment by rthallisey** [comment]
The user didn't have the proper permissions to view resources in another namespace.
```oc adm policy add-cluster-role-to-user cluster-admin admin```
