### ISSUE TITLE
allow rootless operation

### ISSUE THREAD

**Issue by akostadinov** [fusor/ansible-playbook-bundle#188]
Hi, it is important to allow rootless operation of the tool. In many corporate environments the users are not allowed to have root. Having access to dockersocket makes easy for user to obtain root privileges.

Perhaps look at [rootless containers](https://www.cyphar.com/blog/post/20160627-rootless-containers-with-runc)?

**Comment by rthallisey** [comment]
@akostadinov good suggestion. I think it's worth looking at.

**Comment by jianzhangbjz** [comment]
+1, @rthallisey Any update? Maybe we can new a card to support this. What do you think?

**Comment by rthallisey** [comment]
We're looking at re writing the apb tool to incorporate the bundle-lib library in the near future.  At that point, I think we'll evaluate the scope of the apb tool and perform a more in depth security audit so folks can use it in environments that require non root.

**Comment by jianzhangbjz** [comment]
OK, that's great! Thanks!

**Comment by jianzhangbjz** [comment]
@rthallisey Do we have a plan to implement this for 3.11? cc: @chengzhang1016 @zihantang-rh

**Comment by rthallisey** [comment]
The [automationbroker/sbcli](https://github.com/automationbroker/sbcli) repo has been created.  I think this issue should be copied over there to get picked up.  @jianzhangbjz can you re file the issue?

**Comment by rthallisey** [comment]
Copied over the issue,, closing
