### ISSUE TITLE
Repurpose ansible-playbook-bundle repo as only an apb config rendering tool

### ISSUE THREAD

**Issue by rthallisey** [fusor/ansible-playbook-bundle#2]
The ansible-playbook-bundle repo has a bunch of extra files in it that have nothing to do with rendering APB Dockerfiles with the encoded config data.  I think we should clean up this repo so that it only focuses on being a helpful tool for rendering APBs.

**Comment by rthallisey** [comment]
Do we need all the rpm build stuff in this repo?

**Comment by jmrodri** [comment]
I want the .tito and rpm stuff in there. Makes it way easier to build. That works best with tito.

**Comment by jmrodri** [comment]
basically tito will be used to do the rpm releases and tag the versions. It actually makes it easier to release rpms this way.

**Comment by jmontleon** [comment]
+1 for keeping the rpm spec and tito stuff. I know some projects don't like keeping this stuff in the same repo, but it's a royal pain keeping it in sync when it comes downstream if it lives somewhere else.

**Comment by jmrodri** [comment]
Closing as we plan on keeping the .tito build stuff in the repo.
