### ISSUE TITLE
Pushing to broker on minishift rejected

### ISSUE THREAD

**Issue by cunningt** [fusor/ansible-playbook-bundle#201]
Trying to use the apb tool to push to the broker on minishift - I haven't had luck with push without the -o or with --secure either.    I've tried logging in through oc as developer, system, and admin, and none of those options seem to work.

tcunning@tcunning-OSX:/tmp/my-test-apb$ apb push -o
version: 1.0
name: my-test-apb
description: This is a sample application generated by apb init
bindable: False
async: optional
metadata:
  displayName: my-test
plans:
  - name: default
    description: This default plan deploys my-test-apb
    free: True
    metadata: {}
    parameters: []
Exception occurred trying to find docker-registry service in namespace default: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 16 Jan 2018 20:36:05 GMT', 'Content-Length': '122', 'Content-Type': 'text/plain', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store'})
HTTP response body: User "developer" cannot get services in the namespace "default": User "developer" cannot get services in project "default"

Failed to find registry service IP address.
Exception occurred! Unable to get registry IP from namespace default

STEPS TO REPRODUCE - 

Install the minishift addon (https://github.com/sabre1041/cdk-minishift-utils)
Start minishift -
MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --openshift-version=v3.7.0 --service-catalog --memory 4GB

You should see the ASB deployed at the end of your startup log -
-- Applying addon 'ansible-service-broker':.......
Ansible Service Broker Deployed

Configure apb tool (see ansible-playbook-bundle directions)
apb init my-test-apb
cd my-test-apb
apb prepare
apb build
apb push -o / apb push --secure / apb push (I may be doing something wrong here in this step, but I'm not sure what)

**Comment by dymurray** [comment]
Hey Tom,

With the latest RPM build (as of in the last hour) `apb push -o` no longer exists. We removed this to end confusion between the two ways one could "push" an APB.

You need to be logged in as a `cluster-admin` user on OCP that has a valid auth token (`oc whoami -t` and cannot be `system:admin`).  Assuming you are logged in, you can then just do `apb push` which will push the container image to the `openshift` namespace. We fixed a good amount of bugs in the last release so if you can update and try again we might get a better error message.

**Comment by rthallisey** [comment]
@cunningt if you're still seeing the same issue after you do what @dymurray mentioned above then please re open the issue.
