### ISSUE TITLE
apb push fails with "Exception occurred! 'NoneType' object has no attribute 'split'"

### ISSUE THREAD

**Issue by jonnyfiveiq** [fusor/ansible-playbook-bundle#237]
Hello,

Following the example word for word here https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/docs/getting_started.md

apb push fails as follows;

$ apb push
# apb.yml
version: 1.0
name: my-test-apb
description: This is a sample application generated by apb init
bindable: False
async: optional
metadata:
  displayName: my-test
plans:
  - name: default
    description: This default plan deploys my-test-apb
    free: True
    metadata: {}
    parameters: []
Found registry IP at: 172.30.1.1:5000
Finished writing dockerfile.
Building APB using tag: [172.30.1.1:5000/openshift/my-test-apb]
Successfully built APB image: 172.30.1.1:5000/openshift/my-test-apb
Exception occurred! 'NoneType' object has no attribute 'split'

**Comment by StevenTobin** [comment]
I hit this issue when my user didn't have the correct roles. I fixed it by doing this

`oc login -u system:admin`
`oc adm policy add-cluster-role-to-user cluster-admin developer`
`oc adm policy add-cluster-role-to-user access-asb-role developer`
`oc login -u developer -p developer`

**Comment by dymurray** [comment]
This error is caused when the logged in user doesn't have an associated authentication token. You can see if your user has this by typing `oc whoami -t`. This issue was just fixed in master 3 days ago to output a better error. Please switch to a user with proper permissioning that has an auth token. Following @StevenTobin's instructions should get you there.

**Comment by dymurray** [comment]
This is fixed in: https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/pull/233

**Comment by jonnyfiveiq** [comment]
Ok, followed @StevenTobin suggestion, but still fails as follows (different error though);

version: 1.0
name: my-test-apb
description: This is a sample application generated by apb init
bindable: False
async: optional
metadata:
  displayName: my-test
plans:
  - name: default
    description: This default plan deploys my-test-apb
    free: True
    metadata: {}
    parameters: []
Found registry IP at: 172.30.1.1:5000
Finished writing dockerfile.
Building APB using tag: [172.30.1.1:5000/openshift/my-test-apb]
Successfully built APB image: 172.30.1.1:5000/openshift/my-test-apb
Error accessing the docker API. Is the daemon running?
Exception occurred! 500 Server Error: Internal Server Error ("Get http://172.30.1.1:5000/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)")

**Comment by jonnyfiveiq** [comment]
excuse my error...I simply had not run apb push within eval $(minishift docker-env), works fine. thanks
