### ISSUE TITLE
apb list is broken due to exception in get_asb_route()

### ISSUE THREAD

**Issue by beekhof** [fusor/ansible-playbook-bundle#283]
# apb list
Exception occurred! unsupported operand type(s) for +: 'NoneType' and 'str'
#

I traced this to a problem in get_asb_route()
Replacing https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/09e689e0bccda955834f242875d66ddf1fc12ebb/src/apb/engine.py#L407

   if 'asb' in route.metadata.name and 'etcd' not in route.metadata.name:

with
   if 'ansible-service-broker' in route.metadata.name and 'etcd' not in route.metadata.name:

resulted in the correct output.  Perhaps a version mismatch?

 # apb version
Version: apb-1.1.15

 # oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0-alpha.0+f3ca235-917
kubernetes v1.10.0+b81c8f8

**Comment by dymurray** [comment]
Hm... the route should be named asb-1338 unless I'm mistaken... so I'm not sure how this would work? `route.metadata.name` I believe returns asb-1338 on my calls. Would you mind printing out what that returns for you?
