### ISSUE TITLE
ASB installation

### ISSUE THREAD

**Issue by pkliczewski** [fusor/ansible-playbook-bundle#318]
I installed asb by calling:
curl https://raw.githubusercontent.com/openshift/ansible-service-broker/master/apb/install.yaml | oc create -f -

and the asb was deployed to `automation-broker` namespace which is not working with apb tool because it expects one of namespaces defined here https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/src/apb/engine.py#L386

**Comment by pkliczewski** [comment]
I changed https://github.com/openshift/ansible-service-broker/blob/master/apb/install.yaml#L39 to `      args: [ "provision", "--extra-vars", '{ "broker_name": "openshift-automation-service-broker" }' ]` and redeployed to expected namespace. I see:

> [root@localhost ~]# oc get routes -n openshift-automation-service-broker
> NAME                HOST/PORT                                                                                PATH      SERVICES                             PORT        TERMINATION   WILDCARD
> broker              broker-openshift-automation-service-broker.router.default.svc.cluster.local                       openshift-automation-service-broker   port-1338   reencrypt     None
> broker-redirector   broker-redirector-openshift-automation-service-broker.router.default.svc.cluster.local             openshift-automation-service-broker   port-1337                 None

but when I run the apb tool I get:

> [root@localhost ~]# apb broker catalog
> ERRO Failed to get broker route: Failed to find route with name [broker] in namespace [openshift-automation-service-broker]

**Comment by dymurray** [comment]
Hey @pkliczewski, based on your response it looks like you are using the newer version of this tool (1.9.x which will be released as 2.0 with 3.11). We are moving development efforts to https://github.com/automationbroker/apb. We now have an option `apb config` which allows you to configure the route name, the broker name, and a few other options so that the tool works on your cluster. Please let me know if you find some help with that and if you still run into issues file the issue there. 

Thanks.

**Comment by pkliczewski** [comment]
@dymurray Yes, it seems that I am using `https://copr-be.cloud.fedoraproject.org/results/%40ansible-service-broker/ansible-service-broker-latest/epel-7-x86_64/` repo which provides 1.9.3-1.20180821213449.

**Comment by pkliczewski** [comment]
@dymurray I downgraded apb tool to apb-1.3.1
and now getting:
> Contacting the ansible-service-broker at: https://broker-openshift-automation-service-broker.router.default.svc.cluster.local/v2/catalog
> Error: Attempt to list APBs in the broker returned status: 503

I will investigate above issue and closing this one.
