### ISSUE TITLE
yaml vs yml

### ISSUE THREAD

**Issue by mjudeikis** [fusor/ansible-playbook-bundle#76]
Failure in examples due naming in yaml vs yml
` playbook: /opt/apb/actions/**provision.yaml** could not be found`

```
root@ip-172-18-10-234 rds-mysql-apb]# docker run -it --entrypoint="/bin/bash" docker.io/mangirdas/apb-example
ls -la /opt/apb/actions/
-rw-r--r--. 1 root root 232 Jul 21 22:26 deprovision.yml
drwxr-xr-x. 2 root root  23 Jul 21 22:26 group_vars
-rw-r--r--. 1 root root 213 Jul 21 22:26 **provision.yml**
```

**Comment by fabianvf** [comment]
Hmm, I think it checks for both .yaml and .yml playbooks, but I don't think we suppress the error message if we don't find the .yaml. Could you post the full log of the APB? It shouldn't have crashed if provision.yml existed.

**Comment by codificat** [comment]
I believe that fusor/apb-examples#102 addressed this confusion, so closing the issue.

If that wasn't the full fix please feel free to reopen and comment with the details/logs. Thanks!
