### ISSUE TITLE
apb init got "Exception occurred! 'str object' has no attribute 'keys'"

### ISSUE THREAD

**Issue by ghost** [fusor/ansible-playbook-bundle#78]
apb init my_apb -p name=my_apb_param,type=string,default=foo_param,description="sample description" --async=optional --bindable --org my_organization
Initializing /home/wjiang/git/ansible-playbook-bundle/my_apb for an APB.
Exception occurred! 'str object' has no attribute 'keys'

Version: 
apb (0.2.0)

```python
>>> template.render(apb_dict=apb_dict, params=params)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/apb/dat/apb.yml.j2", line 14, in top-level template code
    {% for pair in param.values()[0].keys() -%}{{ pair }}: {{ param[param.keys()[0]][pair] }}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'keys'
```

**Comment by dymurray** [comment]
@wjiangjay We have removed initialization with parameters since the multi-plan approach will eliminate how we declare params. I was able to run `apb init my_apb --async=optional --bindable --org my_organization` without getting an error. This issue is out of date so I am going to close it.
